cleaned up overall design and linked about view to main content view
Cascadia-Mobile-App-Projects/YUP253 pull request #18
Opened 2021-05-04 00:54 UTC by SPJ425cascadia

2021-05-04 04:44 UTC, adamkohler approved these changes
Sean my only concern is the blue text buttons on the bottom of the About view, down the road we may want to change the color scheme so the text stands out better from the background but im good for this to be merged.

2021-05-04 04:58 UTC, antondtran approved these changes

2021-05-04 05:43 UTC, gomezfox requested changes
Overflows vertically on older devices, may be solved using `Spacer`

2021-05-04 05:43 UTC, gomezfox commented on YUP253/About.swift
Padding of 200 overflows screen on older devices, 
* Recommend changing the Image padding to a smaller value (the desired top padding)
* Then to automatically line the rest of the items at the bottom, use the `Spacer(minLength: 0)` in line 32

2021-05-07 05:24 UTC, jdlacy approved these changes
Looks fine

2021-05-10 03:27 UTC, gomezfox approved these changes

2021-05-10 04:54 UTC, merged